[package]
name = "commit_analyzer"
version = "0.1.0"
authors = ["Jan-Erik Rediger <janerik@fnordig.de>"]

[dependencies]
clog = { git = "https://github.com/semantic-rs/clog-lib", branch = "public-raw-parsing" }
